apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutriplan-frontend
  labels:
    app: nutriplan-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutriplan-frontend
  template:
    metadata:
      labels:
        app: nutriplan-frontend
    spec:
      containers:
        - name: nutriplan-frontend
          image: nutriplan-frontend:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
