apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nutriplan-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: nutriplan.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nutriplan-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nutriplan-frontend
                port:
                  number: 80
